AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Teachers Pet API
Globals:
  Function:
    Runtime: nodejs10.x
    Environment:
      Variables:
        SESSION_TABLE:
          Ref: SessionTable
        QUESTION_TABLE:
          Ref: QuestionTable
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
Resources:
  CreateSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.createSession
      FunctionName: CreateSessionFunction
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonSQSFullAccess
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /session/create
            Method: get
      CodeUri: s3://460163561631-us-west-2-kamn-serverless-workload/c0358cc67b59f82eac44e4d1b0c7c1cf
  JoinSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.joinSession
      FunctionName: JoinSessionFunction
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /session/join
            Method: get
      CodeUri: s3://460163561631-us-west-2-kamn-serverless-workload/c0358cc67b59f82eac44e4d1b0c7c1cf
  GetQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.getQuestion
      FunctionName: GetQuestionFunction
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonSQSFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /questions
            Method: get
      CodeUri: s3://460163561631-us-west-2-kamn-serverless-workload/c0358cc67b59f82eac44e4d1b0c7c1cf
  SessionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Sessions
      PrimaryKey:
        Name: session_id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  QuestionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Questions
      PrimaryKey:
        Name: question_id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  ApiUrl:
    Description: URL of the Prod stage of the API endpoint
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
